//
//  RangersAPMSceneTrace.h
//  HeimdallrFinder
//
//  Created by xuminghao.eric on 2023/8/10.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface RangersAPMSceneSpan : NSObject

/**
 A name to identify the span.
 */
@property (atomic, copy) NSString *spanName;

/**
 The begin time of the span. The value should be generated by [[NSDate date] timeIntervalSince1970]
 */
@property (nonatomic, assign) NSTimeInterval beginTime;

/**
 The end time of the span. The value should be generated by [[NSDate date] timeIntervalSince1970]
 */
@property (nonatomic, assign) NSTimeInterval endTime;

@end


@interface RangersAPMSceneTrace : NSObject

/**
 Spans of current trace.
 */
@property (nonatomic, strong, readonly) NSArray<RangersAPMSceneSpan *> *spans;

/**
 A name to identify the scene which is being traced.
 */
@property (nonatomic, copy, readonly) NSString *sceneName;

/**
 Timeout interval of a trace. The trace will be ended with unsuccess after the interval.
 */
@property (nonatomic, assign, readonly) NSTimeInterval timeoutInterval;

/**
 Generate a trace with a name to identify the scene being traced and a interval to end current trace when timeout.
 */
+ (instancetype)traceOfScene:(NSString *)sceneName withTimeoutInterval:(NSTimeInterval)interval;
- (id)init __attribute__((unavailable("please use traceOfScene:withTimeoutInterval:")));
+ (instancetype)new __attribute__((unavailable("please use traceOfScene:withTimeoutInterval:")));

/**
 Begin a trace with a flag to identify whether the scene is loaded for the first time.
 */
- (void)beginForFirstTime:(BOOL)firstTime;

/**
 Add a span to current trace.
 */
- (void)addSpan:(RangersAPMSceneSpan *)span;

/**
 End current trace with a flag of the scene state. The spans will be recorded and then cleared.
 */
- (void)endWithSuccess:(BOOL)success;

@end

NS_ASSUME_NONNULL_END
